spring:
  datasource:
    poolName: zhouyi-pool
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.152:1521:CAIJI
    user: tiger
    password: tiger

    #driverClassName: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/zhouyi?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;autoReconnectForPools=true&amp;failOverReadOnly=false
    #user: root
    #password:
    autoCommit: false
    minIdle: 5
    maximumPoolSize: 20
    connectionInitSql: select 1
    testConnectionOnCheckout: false
    testConnectionOnCheckin: true
    idleConnectionTestPeriod: 30

server:
  context-path: /caijijava
  port: 8060
  tomcat:
    max-http-header-size: -1
mybatis:
  mapperLocations: classpath*:com/zhouyi/business/core/mapper/*.xml

myConfig:
  downloadPath: f://
  uploadPath: f://data/zhouyi-wx/files



#配置JWT的密钥和签发人
com:
  jwt:
    secret: a1b2c3d4
    issuer: lianteng
    #配置JWT信息置换的时间
    retoken: 15*60*1000

caijijava:
  elasticsearch:
    hostlist: ${eshostlist:192.168.1.152:9200} #多个结点中间用逗号分隔




dataSet1:
  name: 手机终端
  className: LedenCollectPTerminal

dataSet2:
  name: 通讯录
  className: LedenCollectPAddressbook

dataSet3:
  name: 通话记录
  className: LedenCollectPCallrecords

dataSet4:
  name: 短信记录
  className: LedenCollectPMessagerecords

#定义数据集对应的类
own:
  #模型层路径
  modelClassPath: com.zhouyi.business.core.model
  #bcp文件路径
  realPath: C:\Users\lenovo\Desktop\Bcp\20190621112602_C__Users_Administrator_Desktop_Backup
  #编码标识
  codes:
    I050008: CJMBBH #手机取证采集目标编号
    C010010: ZZS_DWMC #厂商名称
    G020013: 00000 #厂商组织机构代码
    B010001: 00001 #对象姓名
    B030004: 00000 #对象证件类型
    B030005: 00000 #对象证件号码
    H010014: 00000 #采集时间
    E020012: 00000 #采集人姓名
    B010028: 00000 #负责人证件号码
    G020032: 00000 #管辖地网安部门
    I050001: 00000 #案件编号
    I050003: 00000 #案件类型
    I050002: 00000 #案件名称

    C010001: WPMC #设备名称
    C050001: IMEI_WPBZH #IMEI/ESN/MEID
    C040002: MACDZ #终端MAC地址
    C040006: LY_MACDZ #蓝牙MAC地址
    C010003: WPXH #型号
    C010009: WPTZMS #特征描述

    B020005: YDDH #本机号码
    B020007: 00000 #SIM卡IMSI
    B020020: 00000 #短信中心号码
    H010029: XXSC_PDBZ #删除状态
    B040033: XXSC_CLSJ #删除时间

    J020011: 00000 #通讯录ID
    B070002: GXR_XM #联系人姓名
    H100034: SMXSZ #加密状态

    I010051: TXLZDLXDM #通讯录字段类型
    B020017: LXDHLX #字段标签
    B070003:
      - GXRLXFS #字段值
      - GXR_YDDH #对方号码
    B020019: THZT #通话状态
    H040002: BDSJBS #本地动作
    H010015: KSSJ  #通话开始时间
    H010016: JSSJ #通话结束时间
    H010030: THSC #通话时长

    H030008: DXSFSJ #发送时间
    H040001: DX_JYQK #短消息内容
    H030009: CKZT #查看状态
    H030010: DXCCWZ #存储位置



file:
  upload-location: /home/shenjun/uploads  #/home/shenjun/uploads
  upload-location-temp: /home/shenjun/uploads/temp  #/home/shenjun/uploads/temp


logging:
  level:
    com.zhouyi.business.core.mapper: debug
multipart:
  max-file-size: 100Mb
  max-request-size: 100Mb


finger:
  dir: /home/leden/finger
  ftp:
    dir: /finger/old/
    user: test
    password: 123456
    ip: 192.168.1.152
    port: 21

xmlParse:
    ftp:
      path: ftp://test:123456@192.168.1.152/dist/
